version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: invoice_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - invoice_network

  # Next.js Application
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      # Database
      DATABASE_URL: "postgresql://postgres:password@db:5432/invoice_db"
      
      # NextAuth.js
      NEXTAUTH_URL: "http://localhost:8000"
      NEXTAUTH_SECRET: "your-secret-key-change-this-in-production"
      
      # OAuth Providers (replace with your actual credentials)
      GOOGLE_CLIENT_ID: "your-google-client-id"
      GOOGLE_CLIENT_SECRET: "your-google-client-secret"
      GITHUB_CLIENT_ID: "your-github-client-id"
      GITHUB_CLIENT_SECRET: "your-github-client-secret"
      
      # SMTP Email Configuration
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USER: "your-email@gmail.com"
      SMTP_PASS: "your-app-password"
      SMTP_FROM: "your-email@gmail.com"
      
      # Supabase
      NEXT_PUBLIC_SUPABASE_URL: "your-supabase-project-url"
      NEXT_PUBLIC_SUPABASE_ANON_KEY: "your-supabase-anon-key"
      SUPABASE_SERVICE_ROLE_KEY: "your-supabase-service-role-key"
      
      # App Configuration
      NEXT_PUBLIC_APP_URL: "http://localhost:8000"
    depends_on:
      - db
    networks:
      - invoice_network
    volumes:
      - ./prisma:/app/prisma

volumes:
  postgres_data:

networks:
  invoice_network:
    driver: bridge
